
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GameOntologyServer", targetNamespace = "http://example", wsdlLocation = "file:/X:/X/GitHub/WSproject/TestWebservices/src/example/GameOntologyServer.wsdl")
public class GameOntologyServer_Service
    extends Service
{

    private final static URL GAMEONTOLOGYSERVER_WSDL_LOCATION;
    private final static WebServiceException GAMEONTOLOGYSERVER_EXCEPTION;
    private final static QName GAMEONTOLOGYSERVER_QNAME = new QName("http://example", "GameOntologyServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/X:/X/GitHub/WSproject/TestWebservices/src/example/GameOntologyServer.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAMEONTOLOGYSERVER_WSDL_LOCATION = url;
        GAMEONTOLOGYSERVER_EXCEPTION = e;
    }

    public GameOntologyServer_Service() {
        super(__getWsdlLocation(), GAMEONTOLOGYSERVER_QNAME);
    }

    public GameOntologyServer_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAMEONTOLOGYSERVER_QNAME, features);
    }

    public GameOntologyServer_Service(URL wsdlLocation) {
        super(wsdlLocation, GAMEONTOLOGYSERVER_QNAME);
    }

    public GameOntologyServer_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAMEONTOLOGYSERVER_QNAME, features);
    }

    public GameOntologyServer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GameOntologyServer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GameOntologyServer
     */
    @WebEndpoint(name = "GameOntologyServer")
    public GameOntologyServer getGameOntologyServer() {
        return super.getPort(new QName("http://example", "GameOntologyServer"), GameOntologyServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GameOntologyServer
     */
    @WebEndpoint(name = "GameOntologyServer")
    public GameOntologyServer getGameOntologyServer(WebServiceFeature... features) {
        return super.getPort(new QName("http://example", "GameOntologyServer"), GameOntologyServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAMEONTOLOGYSERVER_EXCEPTION!= null) {
            throw GAMEONTOLOGYSERVER_EXCEPTION;
        }
        return GAMEONTOLOGYSERVER_WSDL_LOCATION;
    }

}
