
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GameOntologyServerService", targetNamespace = "http://example/", wsdlLocation = "http://localhost:9000/GameOntologyServer?wsdl")
public class GameOntologyServerService
    extends Service
{

    private final static URL GAMEONTOLOGYSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException GAMEONTOLOGYSERVERSERVICE_EXCEPTION;
    private final static QName GAMEONTOLOGYSERVERSERVICE_QNAME = new QName("http://example/", "GameOntologyServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/GameOntologyServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAMEONTOLOGYSERVERSERVICE_WSDL_LOCATION = url;
        GAMEONTOLOGYSERVERSERVICE_EXCEPTION = e;
    }

    public GameOntologyServerService() {
        super(__getWsdlLocation(), GAMEONTOLOGYSERVERSERVICE_QNAME);
    }

    public GameOntologyServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAMEONTOLOGYSERVERSERVICE_QNAME, features);
    }

    public GameOntologyServerService(URL wsdlLocation) {
        super(wsdlLocation, GAMEONTOLOGYSERVERSERVICE_QNAME);
    }

    public GameOntologyServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAMEONTOLOGYSERVERSERVICE_QNAME, features);
    }

    public GameOntologyServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GameOntologyServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GameOntologyServer
     */
    @WebEndpoint(name = "GameOntologyServerPort")
    public GameOntologyServer getGameOntologyServerPort() {
        return super.getPort(new QName("http://example/", "GameOntologyServerPort"), GameOntologyServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GameOntologyServer
     */
    @WebEndpoint(name = "GameOntologyServerPort")
    public GameOntologyServer getGameOntologyServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example/", "GameOntologyServerPort"), GameOntologyServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAMEONTOLOGYSERVERSERVICE_EXCEPTION!= null) {
            throw GAMEONTOLOGYSERVERSERVICE_EXCEPTION;
        }
        return GAMEONTOLOGYSERVERSERVICE_WSDL_LOCATION;
    }

}
